project_id = "jahlyvuxftafdwssgkyd"

[functions.analyze-product]
verify_jwt = false

[functions.extract-image-features]
verify_jwt = false

[functions.generate-personas]
verify_jwt = false

[functions.what-if-simulation]
verify_jwt = false

[functions.generate-analytics-insights]
verify_jwt = false

[functions.regenerate-apparel-personas]
verify_jwt = false
